plugins {
    alias libs.plugins.android.app
    alias libs.plugins.compose
    alias libs.plugins.screenshot
}

android {
    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = libs.versions.compose.compiler.get()
    }

    experimentalProperties['android.experimental.enableScreenshotTest'] = true
}

tasks.named('check') {
    dependsOn tasks.named('validateScreenshotTest')
}

dependencies {
    implementation buildLibs.astring.core
    implementation buildLibs.astring.compose
    implementation libs.androidx.appcompat

    implementation libs.androidx.activity.compose
    implementation libs.androidx.compose.material
    implementation libs.androidx.compose.ui.preview
    debugImplementation libs.androidx.compose.ui.tooling

    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test
    androidTestImplementation libs.bundles.testing.android

    screenshotTestImplementation libs.androidx.compose.ui.tooling
    screenshotTestImplementation libs.screenshot.validation.api
}
