pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }

    includeBuild 'gradle/convention'
}

plugins {
    id 'xyz.tynn.convention.settings' version "$xyzTynnConventionVersion"
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

include ':astring:bom'
include ':astring:catalog'

include ':binding:adapters'
include ':compose'

include ':extension:core'
include ':extension:appcompat'
include ':extension:material'

includeBuild 'integration'

rootProject.name = 'AString'
