plugins {
    alias libs.plugins.android
    alias libs.plugins.android.kapt
}

android {
    namespace = "${group}.binding.adapters"

    buildFeatures {
        androidResources = true
        dataBinding = true
    }

    buildTypes {
        databinding {
            matchingFallbacks = ['release']
        }
    }

    flavorDimensions += 'source'
}

androidComponents {
    beforeVariants(selector().all()) {
        enable = buildType == 'databinding'
    }
}

if (!System.getProperty('idea.sync.active')?.toBoolean()) {
    final adapters = project
    rootProject.subprojects {
        if (project != adapters) {
            adapters.evaluationDependsOn(path)
        }

        if (pluginManager.hasPlugin('binding-adapters')) {
            adapters.android {
                productFlavors.register name
                sourceSets.named(name) {
                    root = "$projectDir/src/main"
                }
            }

            final adaptersApi = "${name}Api"
            configurations {
                api.dependencies.configureEach {
                    adapters.dependencies.add adaptersApi, it
                }
            }
        }
    }
}

afterEvaluate {
    final emptyTasks = ['assemble', 'build', 'check', 'lint', 'test']
    tasks.matching {
        it.name in emptyTasks
    }.configureEach {
        enabled = false
        dependsOn.clear()
    }
}
