[plugins]
android = "com.android.library:7.4.2"
kotlin = "org.jetbrains.kotlin.android:1.8.10"
publish = "io.github.gradle-nexus.publish-plugin:1.3.0"
versions = "com.github.ben-manes.versions:0.46.0"

[libraries]
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-core = "androidx.core:core:1.9.0"
androidx-fragment = "androidx.fragment:fragment:1.5.5"
androidx-test-rules = "androidx.test:rules:1.5.0"
google-material = "com.google.android.material:material:1.8.0"

kotlin-stdlib.module = "org.jetbrains.kotlin:kotlin-stdlib"
kotlin-test.module = "org.jetbrains.kotlin:kotlin-test-junit"

test-junit = "junit:junit:4.13.2"
test-mockk = "io.mockk:mockk:1.13.4"
test-slf4j = "org.slf4j:slf4j-nop:2.0.6"

[bundles]
testing = ["kotlin-test", "test-junit", "test-mockk", "test-slf4j"]
