[versions]
android = "7.4.1"
kotlin = "1.8.10"

[plugins]
android = { id = "com.android.library", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
publish = "io.github.gradle-nexus.publish-plugin:1.1.0"
versions = "com.github.ben-manes.versions:0.45.0"

[libraries]
androidx-appcompat = "androidx.appcompat:appcompat:1.6.0"
androidx-core = "androidx.core:core:1.9.0"
androidx-fragment = "androidx.fragment:fragment:1.5.5"
androidx-test-rules = "androidx.test:rules:1.5.0"
google-material = "com.google.android.material:material:1.8.0"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
test-junit = "junit:junit:4.13.2"
test-mockk = "io.mockk:mockk:1.13.4"

[bundles]
testing = ["kotlin-test", "test-junit", "test-mockk"]
