[versions]
android = "7.4.2"
compose-compiler = "1.4.4"

[plugins]
android = { id = "com.android.library", version.ref = "android" }
kotlin = "org.jetbrains.kotlin.android:1.8.10"
publish = "io.github.gradle-nexus.publish-plugin:1.3.0"
versions = "com.github.ben-manes.versions:0.46.0"

[libraries]
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-compose-ui = "androidx.compose.ui:ui:1.4.0"
androidx-core = "androidx.core:core:1.9.0"
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-databinding-common = { module = "androidx.databinding:databinding-common", version.ref = "android" }
androidx-fragment = "androidx.fragment:fragment:1.5.6"
androidx-test-core = "androidx.test:core:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
google-material = "com.google.android.material:material:1.8.0"
junit = "junit:junit:4.13.2"
kotlin-stdlib.module = "org.jetbrains.kotlin:kotlin-stdlib"
kotlin-test.module = "org.jetbrains.kotlin:kotlin-test-junit"
mockk = "io.mockk:mockk:1.13.4"
slf4j = "org.slf4j:slf4j-nop:2.0.7"

[bundles]
testing = ["kotlin-test", "junit", "mockk", "slf4j"]
