plugins {
    alias libs.plugins.android.app apply false
    alias libs.plugins.compose apply false
    alias convention.plugins.project
}

allprojects {
    group = 'xyz.tynn.astring.integration'
}

subprojects {
    pluginManager.withPlugin(libs.plugins.android.app.get().pluginId) {
        android.defaultConfig.minSdk 23
        java.toolchain.languageVersion.set JavaLanguageVersion.of(17)
        dependencies { api platform(libs.kotlin.bom) }
    }
}
