pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

plugins {
    id 'xyz.tynn.convention.settings' version "$xyzTynnConventionVersion"
}

dependencyResolutionManagement {
    repositories {
        if (System.env.DEPLOYMENT) maven {
            name = 'deployment'
            url = System.env.DEPLOYMENT
            credentials(HttpHeaderCredentials)
            authentication {
                header(HttpHeaderAuthentication)
            }
            content {
                includeGroup group
            }
        }
        google()
        mavenCentral()
    }

    versionCatalogs {
        libs.from files('../gradle/libs.versions.toml')

        buildLibs {
            from files('../astring/catalog/versions.toml')
            try {
                version 'astring', gradle.parent ?: settings.version
            } catch (ignored) { // includedBuild || not released
                includeBuild '..'
            }
        }
    }
}

include 'binding'
include 'compose'

rootProject.name = 'AString Integration'
