name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15
      - run: gradle wrapper
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: lint
          cache-read-only: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15
      - run: gradle wrapper
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
