name: Build

on:
  pull_request:
    branches:
      - dev
      - int
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: lint
          cache-read-only: true

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: check -xlint
