name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: tynn-xyz/semantic-version@v1
        with:
          versioning: ${{ github.ref }}
        id: semver
      - run: gradle publishReleasePublicationToSonatypeRepository closeSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.semver.outputs.version }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.NEXUS_USERNAME }}
          PROJECT_URL: 'https://github.com/${{ github.repository }}'
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSWORD }}
          SIGNING_KEY: ${{ secrets.PGP_KEY }}

  release:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated library release
          draft: false
          prerelease: false
