name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
    steps:
      - uses: actions/checkout@v7
      - uses: tynn-xyz/semantic-version@v1
        with:
          versioning: ${{ github.ref }}
        id: semver
      - uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true
      - run: ./gradlew createCentralBundleZip publishReleasePublicationToBuildRepository
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.semver.outputs.version }}
          PROJECT_URL: 'https://github.com/${{ github.repository }}'
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSWORD }}
          SIGNING_KEY: ${{ secrets.PGP_KEY }}
      - name: Run curl -F bundle=@central-bundle.zip https://central.sonatype.com/api/v1/publisher/upload
        run: curl -H "Authorization:$CENTRAL_AUTH" -F bundle=@build/maven/central-bundle.zip
          https://central.sonatype.com/api/v1/publisher/upload
          | sed -e 's:.*:DEPLOYMENT=https\://central.sonatype.com/api/v1/publisher/deployment/&/download/:'
          | tee -a "$GITHUB_ENV"
        env:
          CENTRAL_AUTH: ${{ secrets.SONATYPE_TOKEN }}
      - run: ../gradlew check
        working-directory: integration
        env:
          ORG_GRADLE_PROJECT_deploymentAuthHeaderName: Authorization
          ORG_GRADLE_PROJECT_deploymentAuthHeaderValue: ${{ secrets.SONATYPE_TOKEN }}
          ORG_GRADLE_PROJECT_version: ${{ steps.semver.outputs.version }}
